#!/bin/bash
#SBATCH --job-name=jobcond8s        # create a short name for your job
##SBATCH --output=output_%j.txt       # Standard output (%j = JobID)
#SBATCH --error=error_%j.txt         # Standard error
#SBATCH --nodes=1                # node count
#SBATCH --ntasks=1               # total number of tasks across all nodes
#SBATCH --output=cpus-per-task-16.%j
#SBATCH --partition=simmons_itn18          # Partition/queue name
#SBATCH --qos=preempt
#SBATCH --cpus-per-task=16        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --mem-per-cpu=3G         # memory per cpu-core
#SBATCH --time=120:00:00          # total run time limit (HH:MM:SS)


#SBATCH --mail-type=BEGIN,END,FAIL    # When to send emails: BEGIN, END, FAIL
#SBATCH --mail-user=boyer5@usf.edu  # Replace with your email


hostname
lscpu | grep "Model name"

source ~/miniconda3/etc/profile.d/conda.sh

# Activate PlasPol
conda activate ~/miniconda3/envs/PlasPol

python SARun2_cond8s.py # Use Python 3.9, import mkl
# srun python SARun2_simple.py

conda deactivate

##SBATCH --partition=snsm_itn19
##SBATCH --qos=openaccess

